config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  get 'static_pages/about'

  root to: "static_pages#home" #controller#action

  get '/static_pages' => 'static_pages#home', as: 'static_pages'
  
  get '/welcome' => 'static_pages#welcome', as: 'welcome'

  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  

  resources :songs

  resources :albums

  resources :artists

  resources :genres

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :genre
	belongs_to :artist
	has_many :songs


	mount_uploader :cover, CoverUploader

	extend FriendlyId
  friendly_id :name, use: :slugged

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.paginate(page: params[:page], per_page: 3)
    @genres = Genre.all
    @artists = Artist.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @albums = Album.all
    @genres = Genre.all
    @artists = Artist.all
  end

  # GET /albums/new
  def new
    @album = Album.new
    @albums = Album.all
    @genres = Genre.all
    @artists = Artist.all
  end

  # GET /albums/1/edit
  def edit
    @albums = Album.all
    @genres = Genre.all
    @artists = Artist.all
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :genre_id, :artist_id, :cover)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= bootstrap_form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.collection_select :genre_id, @genres, :id, :name %>
  </div>
  <div class="field">
    <%= f.file_field :cover %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.collection_select :artist_id, @artists, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= image_tag(album.cover_url width: '10%') if album.cover.present? %></td>
        <td><%= album.genre.name %></td>
        <td><%= album.artist.name %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>
<%= will_paginate @albums, renderer: BootstrapPagination::Rails %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>
<p>
	<%= image_tag(@album.cover_url, width: 200) if @album.cover.present? %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @album.genre.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist.name %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>